// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'default_api_key',
    appId: '1:1067949980182:web:420637e8aa56e067b99337',
    messagingSenderId: '1067949980182',
    projectId: 'pw-manager-mongiello',
    authDomain: 'pw-manager-mongiello.firebaseapp.com',
    storageBucket: 'pw-manager-mongiello.firebasestorage.app',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'default_api_key',
    appId: '1:1067949980182:android:a1164910fdef591cb99337',
    messagingSenderId: '1067949980182',
    projectId: 'pw-manager-mongiello',
    storageBucket: 'pw-manager-mongiello.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'default_api_key',
    appId: '1:1067949980182:ios:a787c2a5dcc52894b99337',
    messagingSenderId: '1067949980182',
    projectId: 'pw-manager-mongiello',
    storageBucket: 'pw-manager-mongiello.firebasestorage.app',
    iosBundleId: 'com.example.pwFrontend',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'default_api_key',
    appId: '1:1067949980182:ios:a787c2a5dcc52894b99337',
    messagingSenderId: '1067949980182',
    projectId: 'pw-manager-mongiello',
    storageBucket: 'pw-manager-mongiello.firebasestorage.app',
    iosBundleId: 'com.example.pwFrontend',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'default_api_key',
    appId: '1:1067949980182:web:f8d00587737281deb99337',
    messagingSenderId: '1067949980182',
    projectId: 'pw-manager-mongiello',
    authDomain: 'pw-manager-mongiello.firebaseapp.com',
    storageBucket: 'pw-manager-mongiello.firebasestorage.app',
  );

}